config/routes.rb
Nshvll::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'members#index'

  resources :members do
    get :email, :on => :member
  end

  match 'member/confirm' => 'members#confirm', :as => 'member_confirm'
  match 'member/activate/:activation_code' => 'members#activate', :as => 'member_activate'
  match 'category/:slug' => 'members#by_category', :as => 'category'
  match 'member/edit' => 'members#generate_edit', :as => 'member_generate_edit'
  match 'member/edit/:edit_code' => 'members#edit', :as => 'member_edit'

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :members
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_and_belongs_to_many :categories

  validates_presence_of :name, :email, :url
  validates_attachment_presence :image
  validates_uniqueness_of :email, :on => :create, :message => "That email has been used by another member."
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix

  before_create :generate_activation_code

  scope :recent, order('created_at DESC').limit(5)
  scope :approved, where('active = ?', true)

  has_attached_file :image,
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :styles => { :normal => '200x200#', :small => '100x100#' },
                    :default_style => :normal,
                    :path => ":class/:attachment/:id/:style/:basename.:extension"

  def self.find_by_activation(activation_code)
    self.where('activation = ?', activation_code).first
  end

  def self.find_by_edit_code(code)
    now = Time.now
    cutoff = now - 1800 # edit link is only good for 30 minutes
    self.where('edit_code = ? AND edit_time BETWEEN ? AND ?', code, cutoff, now).first
  end

  def generate_activation_code
    # let's make sure the activation code is SUPER unique
    chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ23456789'
    salt = ''
    20.times { |i| salt << chars[rand(chars.length)] }

    code = Digest::SHA1.hexdigest(Time.now.to_s + salt)

    self.activation = code
  end

  def generate_edit_code
    # let's make sure the edit code is SUPER unique
    chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ23456789'
    salt = ''
    20.times { |i| salt << chars[rand(chars.length)] }

    code = Digest::SHA1.hexdigest(self.email + salt)

    self.update_attributes(:edit_code => code, :edit_time => Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_rand_cookie

  protected
  def set_rand_cookie
    return if !cookies[:rand_seed].blank?
    cookies[:rand_seed] = {:value => rand, :expires => Time.now + 900}
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    seed_val = Member.connection.quote(cookies[:rand_seed])
    Member.connection.execute("select setseed(#{seed_val})")
    @members = Member.approved.order('random()').includes(:categories).page(params[:page]).per(15)
    @categories = Category.order('name')
    @page = params[:page]
  end

  def by_category
    if params[:slug] == 'all'
      redirect_to root_path and return
    end

    @category = Category.find_by_slug(params[:slug])
    if @category.blank?
      flash[:error] = 'The selected category does not exist.'
      redirect_to root_path and return
    end

    @categories = Category.order('name')
    Member.connection.execute("select setseed(#{cookies[:rand_seed]})")
    @members = @category.members.approved.order('random()').includes(:categories).page(params[:page]).per(15)
    @page = params[:page]

    respond_to do |format|
      format.html # by_category.html.erb
      format.js { render :action => 'index' }
    end
  end

  def new
    @member = Member.new
    @member.url = 'http://'
    @categories = Category.order('name')
  end

  def create
    @member = Member.new(params[:member])

    if @member.save
      SiteMailer.member_activation(@member).deliver
      redirect_to member_confirm_path
    else
      @categories = Category.order('name')
      render :action => 'new'
    end
  end

  def edit
    @member = Member.find_by_edit_code(params[:edit_code])
    @categories = Category.order('name')

    if @member.blank?
      flash[:error] = 'Sorry, either your edit link has expired or the listing could not be found.'
      redirect_to root_path
    end
  end

  def update
    @member = Member.find(params[:id])

    if @member.update_attributes(params[:member])
      @member.update_attributes(:edit_code => nil, :edit_time => nil)
      flash[:success] = 'Your listing has been updated!'
      redirect_to root_path
    else
      @categories = Category.all(:order => 'name')
      render :action => 'edit'
    end
  end

  def activate
    member = Member.find_by_activation(params[:activation_code])
    if member
      member.update_attributes(:active => true, :activation => '')
      SiteMailer.member_activated(member).deliver
      flash[:success] = 'Listing activated!'
    else
      flash[:error] = 'A member could not be found with that activation code.'
    end
    redirect_to root_path
  end

  def generate_edit
    if request.post? and params[:email]
      member = Member.find_by_email(params[:email])

      if !member.blank?
        member.generate_edit_code
        SiteMailer.member_edit(member).deliver
        flash[:success] = 'An edit link has been generated and emailed to you.'
        redirect_to root_path
      else
        flash[:error] = "Could not find a listing with that email address."
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= @page_title || 'NSHVLL tech community' %></title>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <link href='/images/nshvll.png' rel='shortcut icon' />

  <%= stylesheet_link_tag 'reset', 'text', 'uniform', 'nshvll' %>
  <%= javascript_include_tag :defaults %>

  <!--[if lte IE 8]>
    <link rel="stylesheet" href="/stylesheets/ie.css" type="text/css" media="screen" />
  <![endif]-->
</head>
<body>
  <div id="container">
    <h1 class="main_h1"><%= link_to 'NSHVLL', root_path %></h1>
    <h1 class="sub_h1">tech community</h1>
    <div class="clear"></div>

    <%- if !flash.blank? -%>
      <%- flash.each do |key, msg| -%>
        <div id="<%= key %>" class="flash">
          <p style="float:right;"><%= link_to_function 'X', "$('##{key}').fadeOut()" %></p>
          <p><%= msg %></p>
          <div class="clear"></div>
        </div>
      <%- end -%>
    <%- end -%>

    <%= yield %>
    <div id="push"></div>
  </div><!-- container -->
  <div id="footer">
    <div id="footer-inner">
      <p class="footer-links"><%= link_to 'Join the Club', new_member_path %></p>
      <p class="byline">
        Created by <%= link_to 'Travis Roberts', 'http://travisonrails.com', :popup => true %>
        &nbsp;|&nbsp;
        Inspired by <%= link_to 'Chris Kalani', 'http://chriskalani.com/', :popup => true %>
        and <%= link_to 'prtlnd.com', 'http://prtlnd.com', :popup => true %>
      </p>
    </div><!-- footer-inner -->
  </div><!-- footer -->

  <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  </script>
  <script type="text/javascript">
    try {
      var pageTracker = _gat._getTracker("UA-15524458-1");
      pageTracker._trackPageview();
    }
    catch(err) {}
  </script>
</body>
</html>

app/views/members/_category_select.html.erb
<div class="category_select_container">
  <p class="category_select_label">Show me</p>
  <select name="category" id="category_select">
    <option value="all">All Members</option>
    <%- @categories.each do |category| -%>
      <option value="<%= category.slug %>" <%= "selected='selected'" if @category === category %>><%= category.name.pluralize %></option>
    <%- end -%>
  </select>
</div><!-- category_select_container -->

<p class="edit_listing">
  <%= link_to 'Edit Your Listing &rarr;'.html_safe, member_generate_edit_path %>
</p>

<div class="clear"></div>

app/views/members/_form.html.erb
<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <span class="hint">Who are you?</span>
</p>
<p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <span class="hint">Required to activate your account. Not shown.</span>
</p>
<p>
    <%= f.label :url, 'Website' %>
    <%= f.text_field :url %>
    <span class="hint">You do have a website, right?</span>
</p>
<p>
  <%= f.label :image, 'Image' %>
  <div class="image_field">
    <%- if @member.image.exists? -%>
      <div><%= image_tag(@member.image.url(:small)) %></div>
    <%- end -%>
    <%= f.file_field :image %>
    <span class="hint">Image will be cropped to a 200x200 square.</span>
  </div>
</p>
<p>
  <label>What are you?</label>
  <ul class="member_categories">
    <%- @categories.each do |category| -%>
      <li>
        <%= check_box_tag 'member[category_ids][]', category.id, @member.categories.include?(category), :id => dom_id(category) %>
        <label for="<%= dom_id(category) %>" class="category_label"><%= category.name %></label>
      </li>
    <%- end -%>
  </ul>
  <span class="hint">Choose <strong>up to 3</strong> categories.</span>
  <span class="small">Don't see your title? <%= mail_to 'nshvlltn@gmail.com', 'Let me know' %>.</span>
</p>

app/views/members/_members.html.erb
<%- @members.each do |member| -%>
  <div class="member_entry">
    <a href="<%= member.url %>" target="_blank">
      <%= image_tag member.image.url %>
      <div class="member_info">
        <span class="name"><%= member.name %></span>
        <%- member.categories.each do |cat| -%>
          <em><%= cat.name %></em>
        <%- end -%>
      </div><!-- member_info -->
    </a>
  </div><!-- member_entry -->
<%- end -%>

app/views/members/_pagination.html.erb
<%= paginate @members %>

app/views/members/by_category.html.erb
<h2 class="category_title" style="display:none;"><%= @category.name.pluralize %></h2>

<%= render :partial => 'category_select' %>

<div id="members">
  <%= render :partial => 'members' %>
</div><!-- members -->

<div class="clear"></div>

<div id="pagination">
  <%= render :partial => 'pagination' %>
</div><!-- pagination -->

app/views/members/confirm.html.erb
<h1>Listing Created</h1>

<p class="confirm">
  You're almost there. An email has been sent to the address you provided with an activation link. Please check your email.
</p>

app/views/members/edit.html.erb
<h1 class="add_listing">Edit Your Listing</h1>

<%= form_for(@member, :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <p class="submit">
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/members/generate_edit.html.erb
<h1 class="add_listing">Edit Your Listing</h1>

<p>Enter the email address you used when you registered. You will be emailed an edit link that is good for 30 minutes. No login required!</p>

<div class="generate_edit_form">
  <%= form_tag member_generate_edit_path do %>
    <p>
      <%= label_tag :email, 'Email Address' %>
      <%= text_field_tag :email, params[:email] %>
    </p>
    <p class="submit"><%= submit_tag 'Submit' %></p>
  <% end %>
</div><!-- generate_edit_form -->

app/views/members/index.html.erb
<%= render :partial => 'category_select' %>

<div id="members">
  <%= render :partial => 'members' %>
</div><!-- members -->

<div class="clear"></div>

<div id="pagination">
  <%= render :partial => 'pagination' %>
</div><!-- pagination -->

app/views/members/index.js.erb
$('#members').append("<div id='page_<%= @page %>' class='new_page'><%= escape_javascript(render("members")) %></div>");
$('#pagination').html("<%= escape_javascript(render("pagination")) %>");

// have to re-do the hover effect (because the 'live' function can't bind the 'hover' action - sucks!)
$(document).ready(function() {
  // show and hide member info panels
  $('.member_entry').hover(
    function() {
      var target_div = $(this).find('.member_info');
      var move = 185 - target_div.height();
      $(this).find('.member_info').animate({top:move}, {queue:false, duration:250, easing: 'easeInSine'});
    },
    function() {
      $(this).find('.member_info').animate({top:'160px'}, {queue:false, duration:250, easing: 'easeOutSine'});
    }
  );
  
  // scroll the page down to the new entries
  $("#page_<%= @page %>").scrollThis();
});

app/views/members/new.html.erb
<h1 class="add_listing">Add Yourself</h1>

<p>*All fields are required.</p>
<%= form_for(@member, :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <p class="submit">
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/user_sessions/new.html.erb
<%= form_for @user_session do |form| %>
  <%= form.error_messages %>
  <ul>
    <li>
      <%= form.label :username, "Username" %>
      <%= form.text_field :username %>
    </li>
    <li>
      <%= form.label :password, "Password" %>
      <%= form.password_field :password %>
    </li>
    <li>
      <%= form.submit "Submit" %>
    </li>
  </ul>
<% end %>